#!/bin/bash
backlight="$(cat /sys/class/backlight/intel_backlight/bl_power | sort -u)"

case "$backlight" in
	0)
	# Display ON
	echo "Switching ON CPU Cores 1-3";
	echo 1 > /sys/devices/system/cpu/cpu1/online;
	echo 1 > /sys/devices/system/cpu/cpu2/online;
	echo 1 > /sys/devices/system/cpu/cpu3/online;
	;;
	4)
	# Display OFF
	echo "Switching OFF CPU Cores 1-3";
	echo 0 > /sys/devices/system/cpu/cpu1/online;
	echo 0 > /sys/devices/system/cpu/cpu2/online;
	echo 0 > /sys/devices/system/cpu/cpu3/online;
	;;
esac
	
